# Generated by Django 2.1 on 2018-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('members', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='09-06-2018', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('M', models.IntegerField(default=0)),
                ('F', models.IntegerField(default=0)),
                ('X', models.IntegerField(default=0)),
            ],
        ),
    ]
